name: Hello!

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        description: "Name of the person to greet"

jobs:
  A:
    uses: ./.github/workflows/template-hello.yaml
    with:
      name: ${{ github.event.inputs.name }}

  B:
    uses: ./.github/workflows/template-hello.yaml
    if: ${{ github.event.inputs.name == 'B' }}
    with:
      name: ${{ github.event.inputs.name }}
    