name: Hello!

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: string
        description: "Name of the person to greet"

jobs:
  A:
    uses: ./.github/workflows/template-hello.yaml
    with:
      name: ${{ github.event.inputs.name }}

  B:
    uses: ./.github/workflows/template-hello.yaml
    if: ${{ github.event.inputs.name == 'B' }}
    with:
      name: ${{ github.event.inputs.name }}
    
  C:
    runs-on: ubuntu-latest
    outputs:
      greetings: ${{ steps.gr33t.outputs.greetings }}
    steps:
      - name: This is Init
        run: echo "zzz... getting ready..."

      - name: Set output
        id: gr33t
        run: echo "greetings=Hello ${{ inputs.name }}" >> $GITHUB_OUTPUT

  D:
    runs-on: ubuntu-latest
    needs: C
    if: ${{ needs.C.outputs.greetings }} == 'Hello D'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello, ${{ inputs.name }}!"