name: Hello World (template)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: "Name of the person to greet"

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      greetings: ${{ steps.gr33t.outputs.greetings }}
    steps:
      - name: This is Init
        run: echo "zzz... getting ready..."

      - name: Set output
        id: gr33t
        run: echo "::set-output greetings=Hello ${{ inputs.name }}"

  hello:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello, ${{ inputs.name }}!"


  hello-if:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ inputs.name == 'if' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello, ${{ inputs.name }}!"

  hello-if-output:
    runs-on: ubuntu-latest
    needs: init
    if: ${{ needs.init.outputs.greetings == 'Hello if' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello, ${{ inputs.name }}!"