name: Hello World (template)

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
        description: "Name of the person to greet"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Hello World
        run: echo "Hello, ${{ inputs.name }}!"